# Generated by Django 5.0.1 on 2024-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_dislike_count_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
