# Generated by Django 5.0.1 on 2024-02-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_login',
            field=models.BooleanField(default=False),
        ),
    ]
